services:
  - type: web
    name: lastyt
    env: node
    buildCommand: |
      npm install
      # Download yt-dlp binary to the project root during build
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./yt-dlp
      chmod a+rx ./yt-dlp
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: PATH
        value: /opt/render/project/src:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
